import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import { User } from '../user/user.model.js';
import { config } from '../../config/env.config.js';
import { UnauthorizedError, ConflictError } from '../../core/errors/app-error.js';
import type { RegisterInput, LoginInput } from './auth.dto.js';

interface JwtPayload {
  userId: string;
  email: string;
}

interface AuthResponse {
  user: {
    id: string;
    email: string;
    name: string;
  };
  accessToken: string;
  refreshToken: string;
}

export class AuthService {
  /**
   * Generate access token
   */
  private generateAccessToken(payload: JwtPayload): string {
    return jwt.sign(payload, config.jwtSecret, {
      expiresIn: config.jwtExpiresIn as jwt.SignOptions['expiresIn'],
    });
  }

  /**
   * Generate refresh token
   */
  private generateRefreshToken(payload: JwtPayload): string {
    return jwt.sign(payload, config.jwtSecret, {
      expiresIn: '30d' as jwt.SignOptions['expiresIn'],
    });
  }

  /**
   * Hash password
   */
  private async hashPassword(password: string): Promise<string> {
    return bcrypt.hash(password, 10);
  }

  /**
   * Compare password with hash
   */
  private async comparePassword(password: string, hash: string): Promise<boolean> {
    return bcrypt.compare(password, hash);
  }

  /**
   * Register new user
   */
  async register(data: RegisterInput): Promise<AuthResponse> {
    /* Check if user already exists */
    const existingUser = await User.findOne({
      where: { email: data.email },
    });

    if (existingUser) {
      throw new ConflictError('User with this email already exists');
    }

    /* Hash password */
    const hashedPassword = await this.hashPassword(data.password);

    /* Create user */
    const user = await User.create({
      id: '', /* Will be generated by UUIDV4 */
      email: data.email,
      name: data.name,
      password: hashedPassword,
    });

    /* Generate tokens */
    const payload: JwtPayload = {
      userId: user.id,
      email: user.email,
    };

    const accessToken = this.generateAccessToken(payload);
    const refreshToken = this.generateRefreshToken(payload);

    return {
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
      },
      accessToken,
      refreshToken,
    };
  }

  /**
   * Login user
   */
  async login(data: LoginInput): Promise<AuthResponse> {
    /* Find user */
    const user = await User.findOne({
      where: { email: data.email },
    });

    if (!user) {
      throw new UnauthorizedError('Invalid credentials');
    }

    /* Verify password */
    const isPasswordValid = await this.comparePassword(data.password, user.password);

    if (!isPasswordValid) {
      throw new UnauthorizedError('Invalid credentials');
    }

    /* Generate tokens */
    const payload: JwtPayload = {
      userId: user.id,
      email: user.email,
    };

    const accessToken = this.generateAccessToken(payload);
    const refreshToken = this.generateRefreshToken(payload);

    return {
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
      },
      accessToken,
      refreshToken,
    };
  }

  /**
   * Refresh access token
   */
  async refreshToken(token: string): Promise<{ accessToken: string; refreshToken: string }> {
    try {
      /* Verify refresh token */
      const decoded = jwt.verify(token, config.jwtSecret) as JwtPayload;

      /* Check if user still exists */
      const user = await User.findByPk(decoded.userId);

      if (!user) {
        throw new UnauthorizedError('User not found');
      }

      /* Generate new tokens */
      const payload: JwtPayload = {
        userId: user.id,
        email: user.email,
      };

      const accessToken = this.generateAccessToken(payload);
      const refreshToken = this.generateRefreshToken(payload);

      return { accessToken, refreshToken };
    } catch (error) {
      throw new UnauthorizedError('Invalid or expired refresh token');
    }
  }

  /**
   * Verify access token
   */
  async verifyAccessToken(token: string): Promise<JwtPayload> {
    try {
      const decoded = jwt.verify(token, config.jwtSecret) as JwtPayload;
      return decoded;
    } catch (error) {
      throw new UnauthorizedError('Invalid or expired token');
    }
  }

  /**
   * Get user by ID
   */
  async getUserById(userId: string) {
    const user = await User.findByPk(userId, {
      attributes: ['id', 'email', 'name'],
    });

    if (!user) {
      throw new UnauthorizedError('User not found');
    }

    return {
      id: user.id,
      email: user.email,
      name: user.name,
    };
  }
}
